project:
  type: website

website:
  title: "Salary & Compensation Trends"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: salary_disparities.qmd
        text: Salary Disparities
      - href: career_plan.qmd
        text: Career Strategy
      - href: about.qmd
        text: About
format:
  html:
    theme: cosmo
    toc: true