title: "Job Market Analysis 2024"
author: "Group 10"
date: "2025-02-18"
output: html_document


project:
  type: website

website:
  title: "Salary & Compensation Trends"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: salary_disparities.qmd
        text: Salary Disparities
      - href: career_plan.qmd
        text: Career Strategy
      - href: about.qmd
        text: About
      - href: citation.qmd
        text: Citation
format:
  html:
    theme: cosmo
    toc: true