---
title:"references"
---


## Predictive Salary Modelling: Leveraging Data Science Skills and Machine Learning for Accurate Forecasting
M. A. Haseeb, R. Viswanathan, K. Iyer, A. R. Hota and B. P. Prathaban, "Predictive Salary Modelling: Leveraging Data Science Skills and Machine Learning for Accurate Forecasting," 2024 9th International Conference on Communication and Electronics Systems (ICCES), Coimbatore, India, 2024, pp. 1011-1019, doi: 10.1109/ICCES63552.2024.10859447. keywords: {Analytical models;Accuracy;Linear regression;Neural networks;Predictive models;Data science;Prediction algorithms;Data models;Remuneration;Random forests;Data science;Machine Learning;Predictive Salary Modelling},
https://ieeexplore.ieee.org/abstract/document/10859447?casa_token=uzkAFRL6ITUAAAAA:17dSviZPa3PeH7FZYtyzFB7r_uSxglvyaV_I2d8FjpOOu8F2g2A4JDqPturPrlQlsOWBwEf2 

## TACKLING ECONOMIC INEQUALITIES THROUGH BUSINESS ANALYTICS: A LITERATURE REVIEW
Ejuma Martha Adaga, Zainab Efe Egieya, Sarah Kuzankah Ewuga, Adekunle Abiola Abdul, & Temitayo Oluwaseun Abrahams. (2024). TACKLING ECONOMIC INEQUALITIES THROUGH BUSINESS ANALYTICS: A LITERATURE REVIEW. Computer Science & IT Research Journal, 5(1), 60-80. https://doi.org/10.51594/csitrj.v5i1.702
https://fepbl.com/index.php/csitrj/article/view/702

## Antecedent configurations toward supply chain resilience: The joint impact of supply chain integration and big data analytics capability
Jiang, Y., Feng, T., & Huang, Y. (2024). Antecedent configurations toward supply chain resilience: The joint impact of supply chain integration and big data analytics capability. Journal of Operations Management, 70(2), 257–284. 
https://doi.org/10.1002/joom.1282

## LEVERAGING AI AND DATA ANALYTICS FOR ENHANCING FINANCIAL INCLUSION IN DEVELOPING ECONOMIES
Adeoye, O. B., Addy, W. A., Ajayi-Nifise, A. O., Odeyemi, O., Okoye, C. C., & Ofodile, O. C. (n.d.). Leveraging AI and data analytics for enhancing financial inclusion in developing economies. Finance & Accounting Research Journal. https://fepbl.com/index.php/farj/article/view/856 
https://doi.org/10.51594/farj.v6i3.856

