project:
  type: website

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Research Rationale"
      - href: introduction.qmd
        text: "Introduction"
      - href: ai_vs_tradsalary_analysis.qmd
        text: "AI vs. Traditional Salary Analysis"
      - href: salaries-differ-across-ai-vs-non-ai-careers.qmd
        text: "Salaries Differ Across AI vs. Non-AI Careers"
      - href: data_analysis.qmd
        text: "Data Cleaning & Exploration"
      - href: eda_updation.qmd
        text: "Exploratory Data Analysis"
      - href: skill_gap_analysis.qmd
        text: "Skill Gap Analysis"
      - href: ml_methods.qmd
        text: "ML Methods"
      - href: nlp_method.qmd
        text: "NLP Methods"
      - href: career_plan.qmd
        text: "Career Plan"
      - href: citation.qmd
        text: "Citations"
      - href: final_report.qmd
        text: "Final Report"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    css: styles.css   