project:
  type: website

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: introduction.qmd
        text: "Introduction"
      - href: data_analysis.qmd
        text: "Data Cleaning & Exploration"
      - href: eda updation.qmd
        text: "Exploratory Data Analysis"
      - href: skill_gap_analysis.qmd
        text: "Skill Gap Analysis"
      - href: ml_methods.qmd
        text: "ML Methods"
      - href: nlp_methods.qmd
        text: "NLP Methods"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    css: styles.css   # <--- Add this here inside html section
